apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gubtom-pvc
spec:
  volumeName: gubtom-pv
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
